title: Uen Media Github
author: Uenmedia
email: I will edit this later
description: > # this means to ignore newlines until "baseurl:"
  Uen Media github pages.

# social links
twitter_username: uenmedia
github_username:  Qurus

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
